### ISSUE TITLE
[question] regarding flashing

### ISSUE THREAD

**Issue by spaivaras** [greatscottgadgets/yardstick#1]
First of all thank you for your awesome projects.
Currently i am building yardstick one by hand, manufactured pcb hand soldered components. The question is how about flashing the bare CC1111.

I only see mansions to GoodFET as a programer, but can I just use any jtag interface for it? Or does GoodFET uses some custom logic while flashing CC1111?

I understand that once I will have boot loader I will be able to install rfcat directly thru usb. But I am a bit lost on initial boot loader upload to CC1111 without GoodFET :)

Thank you

**Comment by dominicgs** [comment]
The tricky part here is that the CC1111 speak a protocol that is similar to JTAG, but not JTAG.  The two adapters that I know support the protocol are the GoodFET and the TI CC Debugger.

**Comment by spaivaras** [comment]
Damn, did some more research, and you are 100% right. I guess next product I will be making is GoodFET itself :D, In any case just ordered a knock off SmartRF04EB it seems they are something that can do "CC debugger" stuff as well. Thank you for the info, I guess this can be closed now.
