### ISSUE TITLE
YardStick One RX  Gain

### ISSUE THREAD

**Issue by rleto577** [greatscottgadgets/yardstick#10]
Hello,

I've been experimenting with the YardStick One and the RTL-SDR (RTL2832U & R820T2-Based Software Defined Radio)
dongle and I noticed that the YardStick One RX RF gain seems to be set too high; consequently, I'm frequently missing packets
with a strong signals. I can adjust the RTL-SDR dongle gain to receive most packets regardless of signal strengths.

How can I adjust the YardStick One RX gain via the RfCat firmware. I tried the change the TESTx and AGCCTRLx values; but,
I can't find values to allow reception and decoding of packets with strong signals.

Thank you in advance for your support.

Regards,

**Comment by mossmann** [comment]
YARD Stick One has a separate LNA chip that can be bypassed with `d.setAmpMode(0)`. I'm guessing that will solve your problem. Other than that, I think you're on the right track with the AGCCTRL2 settings.

**Comment by rleto577** [comment]
Hello Michael,
Thank you for the update and taking time to reply.  What dongle version are you using
to configure the YardStick with the setAmpMode command ?  I am using the following rev. and I don't see any RX gain changes:

>>> print d.reprRadioConfig()
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0464
Compiler:            SDCCv350
Bootloader:          CC-Bootloader
== Software ==
rflib rev:           464

I tried the following combination with three different YardSticks One and I don't
detect any change in RX reception.  I even try to use the RSSI related commands; but,
due to the configuration complexity and commands ambiguity, I cannot rely on the RSSI
commands. So, I merely compare the receptions counts from the same stable RF signal and stable source.

1- Command rem's out
2- d.setAmpMode(0)
3- d.setAmpMode(1)

It's too bad there isn't an easy way to optimally configure and use the CC1111 MCU / Yardstick One. So far I've been using doctor Google and countless experimentation which is time consuming and frustrating to configure the YardStick module for a specific purpose.

Thank you in advance for your support and great products.

R. Letourneau

**Comment by straithe** [comment]
I don't quite understand some of the pieces of your comment. There is only one YARD Stick One dongle version and setAmpMode does not depend on that dongle version. Were you maybe asking about firmware version instead of hardware version?

What do you mean when you say the "command rem's out"? I don't understand what the word rem means here.

What do you mean by doctor Google? Do you mean that you are using Google to look for help, or did you mean something else?

**Comment by rleto577** [comment]
YARD Stick One Firmware:
Have a look at: https://roaldnefs.com/posts/2019/01/update-yard-stick-one-firmware/
-----------------------------------------------------------------------------------

Typo: "rem'd out" not rem's out.

Comment-out or rem'd out:

Meanings
verb (programming) To temporarily disable a section of source code by converting it into a comment.

To disable lines of code in a program by surrounding them with comment-start and comment-stop characters.
Also called "remmed out (rem'd out)." 
----------------------------------------------------------------------------------

Doctor Google:
Using Google to look for help

**Comment by straithe** [comment]
Going back to your original question, the answer is to set `d.setAmpMode(0)` as @mossmann suggested. Dongle version doesn't matter. Please let me know if this answers your question.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
