### ISSUE TITLE
Stopped working after 1 week, 3 Led on solid

### ISSUE THREAD

**Issue by KCarolan** [greatscottgadgets/yardstick#12]
The dongle shows up using dmesg.  Not shure what do try next.

**Comment by straithe** [comment]
You mention that the YARD Stick stops working. Can you give me more detail as to what that means?

**Comment by KCarolan** [comment]
We are all set, we had to reprogram the firmware on the yardstick it's been
working great since then.
 thanks Kevin

**Comment by straithe** [comment]
Thank you for the update. I will close this issue.
