### ISSUE TITLE
Timeout waiting for USB response.

### ISSUE THREAD

**Issue by ghost** [greatscottgadgets/yardstick#13]
I get this error after a minute or so running rfpwn or brookforce 
rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response.
Updated to latest Firmware rev:  0616 Compiler: SDCCv350

My rfcat output is garbled looks almost like HTML. This happened after I updated the firmware and RFcat.
I have looked countless days trying to resolve this I find little to nothing about this and no documentation on the greatscott website about this.

What i have Tried:
Switching from usb 2.0 to 3
Flashing the boot loader to latest version of the .hex file.
Try using a different computer like a desktop running ubuntu or mint. (I use this yardstick one on a RPI4 4GB by default)

I do not have another YS1 to test if it's just my dongle However before the firmware upgrade it used to be way worse with timeouts.
![rfcat2](https://user-images.githubusercontent.com/86231294/133123522-7ab8013e-f963-4f10-a351-4d8d4d20f750.png)

**Comment by straithe** [comment]
Have you asked this question on the rfcat repository as well? https://github.com/atlas0fd00m/rfcat They have made some recent changes that I suspect might be the root of this issue.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
