### ISSUE TITLE
Documentation needs instructions on updating the rfcat firmware

### ISSUE THREAD

**Issue by martinling** [greatscottgadgets/yardstick#17]
There don't seem to be any instructions for this at the moment, but this comment gives an example of how to do it:

https://github.com/atlas0fd00m/rfcat/issues/101#issuecomment-775504496

We'll need something that covers setting up the necessary tools, different operating systems, finding the latest release, etc.

This is needed for users encountering #16, as it seems there's still units out there with that problem.

**Comment by bigoper** [comment]
Same [here](https://github.com/atlas0fd00m/rfcat/issues/47#issuecomment-992055461)
We really need some help, this should be easy but on the surface, it's not.

Thank you!

**Comment by straithe** [comment]
There is a new version of the firmware available: https://github.com/atlas0fd00m/rfcat. Please try it and open a new issue if you continue to have trouble.
