### ISSUE TITLE
LED 1 inactive, and errors

### ISSUE THREAD

**Issue by HackingIntoYourHeart** [greatscottgadgets/yardstick#2]
LED 1 is not active. This YardStick One I bought quit on me after a week. $130, and I'm peeved.

Output, no matter what I try:
Error in resetup():Exception('No Dongle Found. Please insert a RFCAT dongle.',)

I cannot solve this issue. There is nothing on the web describing my problem. I can't enter bootloader mode. This issue is prevalent no matter what computer I try it on. LED 2 and 3 light up, but not one. This doesn't make any sense, as LED 1 means "initialized" and 2 and 3 are regarding TX and RX being active. Can someone PLEASE help me?! I don't know where else to turn!

**Comment by dominicgs** [comment]
Are you on a Linux system?  If so, what happens in `dmesg` when you plug in the YardStick One?

Does it show up in `lsusb` as an OpenMoko device?

**Comment by HackingIntoYourHeart** [comment]
dmesg is no different with, or without the yardstick plugged in, and
neither is lsusb. There is no recognition that the yardstick is even
plugged in.

**Comment by dominicgs** [comment]
Is that the same when you jumper the pins to get it in to bootloader mode?

**Comment by HackingIntoYourHeart** [comment]
"The pins" isn't very specific, but, yes. I have tried every combination of
pins and looked at a couple diagrams to tell me which ones were 7 and 9
(there is one on a random forum on the internet, but i got lucky finding
that), and nothing changes. My computer, no matter what, does not recognize
the yardstick. None of my linux computer's do. Would you mind helping me
figure out which pins are 9 and 7? Or if those are even the correct pins to
connect? Maybe i did it wrong the whole time.

**Comment by dominicgs** [comment]
Pins 7 & 9 are the two highlighted in red in this image:
![ys1_pins](https://user-images.githubusercontent.com/91747/46188253-46eb0580-c2a5-11e8-96a5-5f8dfee1632a.jpg)

I didn't realise we didn't have an image of this on the wiki, I'll add one.

**Comment by HackingIntoYourHeart** [comment]
Just tried it, and... nothing :(

**Comment by dominicgs** [comment]
Sounds like a defective YardStick One.  Possibly a bad solder joint on the CC1111.

I recommend contacting the reseller that sold you the device and asking for a replacement.

**Comment by HackingIntoYourHeart** [comment]
Could you guide me through that? Bought it from Nooelec (think that's how
you spell it?). I bought it months ago as well. Am I just screwed?

**Comment by dominicgs** [comment]
Use their customer support [form](https://support.nooelec.com/hc/en-us/requests/new) and refer them to this thread.

**Comment by HackingIntoYourHeart** [comment]
Alright, thanks! Hopefully I don't to buy a new one. If I do, I'm buying
directly from great scott gadgets! Thank you so much! Have a great night,
day, morning, afternoon, or whatever it is where you are on earth :D

**Comment by mossmann** [comment]
It looks like this was resolved by hardware replacement. Closing.

**Comment by jfdhuiz** [comment]
Just to be clear, if I connect the YS1, I connect pins 7 and 9, and all 3 lights should flash? And if nothing flashes my YS1 is broken?
