### ISSUE TITLE
YARD Stick One Not Found

### ISSUE THREAD

**Issue by cw7664** [greatscottgadgets/yardstick#20]
Hey there,

I cannot get my YS1 to work on Windows 11 or my Ubuntu 20.04 VM (VirtualBox). I have tried following all the documentation on here and the rfcat repository and every forum I could find.

Windows gives me some generic "Device not recognized/damaged" error message and just doesn't show up at all in Ubuntu. I got it to appear on Windows as a COM port when put it into bootloader mode by shorting pins 7 and 9 (all 3 LEDs did light up). However, I was still not able to do anything with it. 

Back in Ubuntu I tried reloading firmware onto the device following [this](https://roaldnefs.com/posts/2019/01/update-yard-stick-one-firmware/) using both the methods described and had no luck. It kept giving me the "Dongle not found" error message when using "$ rfcat -r" or a message along the lines of "Device being used by something else like a manager." Sorry, I am not at my workbench to give you exact messages. But I have tried unplugging and replugging it dozens of times and nothing.

Next, I tried to downgrade my SDCC version from 3.8.0 to 3.5.0, but it could not be found in the repository. 

Then tried installing the libusb-32 drivers using Zadig (along with the other drivers) with and without it in bootloader mode. No cigar. 

I have scoured the internet and tried everything I could find on here and other forums with no success. I don't know if it is not compatible with my updated setup or what.

Thanks in advance.

**Comment by mossmann** [comment]
Based on the fact that the device appeared in Windows in bootloader mode, I think it is very likely that this problem can be solved with a firmware update. I recommend trying to update the firmware using a native Linux installation. Updating the firmware in a Linux VM on top of a Windows host OS may not be possible given the current state of the installed firmware.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
