### ISSUE TITLE
Schematics as PDF

### ISSUE THREAD

**Issue by wimton** [greatscottgadgets/yardstick#22]
Can you please add a PDF version of the schematics and the PCB layout, so the interested can view them without having to download a whole CAD program?

**Comment by straithe** [comment]
Thank you for the suggestion. I will get this done in June as I am about to go on vacation for a few weeks.

**Comment by pickeditmate** [comment]
[azalea.pdf](https://github.com/greatscottgadgets/yardstick/files/8633016/azalea.pdf)
Schematics

**Comment by wimton** [comment]
To [pickeditmate](https://github.com/pickeditmate): the azalea.pdf seems to have little relation to the Yardstick One, but it is a good example of the format.

**Comment by pickeditmate** [comment]
> To [pickeditmate](https://github.com/pickeditmate): the azalea.pdf seems to have little relation to the Yardstick One, but it is a good example of the format.

Sorry about that, was practicing with greatfet how to export. Ive no clue what layers you want for pcb pdf so I'll leave that to the pro's
[yardstickone sch.pdf](https://github.com/greatscottgadgets/yardstick/files/8671280/yardstickone.sch.pdf)

**Comment by wimton** [comment]
Thanks, that is a very usable information on how the components are interconnected! I guess that the people interested in the PCB layers will use a CAD program anyway.
