### ISSUE TITLE
Device not found after a Python exception

### ISSUE THREAD

**Issue by wimton** [greatscottgadgets/yardstick#23]
When an exception is thrown in a Python program, the error: "Error in resetup():USBTimeoutError(110, 'Operation timed out') appears on a subsequent invocation and the YS1 must be unplugged and reinserted.
OS:  Recent Kali on 64-bit Intel. Using Python code, Git from 22-04-2022

**Comment by pickeditmate** [comment]
That's very common, especially when forgetting to set setmodeIDLE() at the end of scripts.

**Comment by straithe** [comment]
@wimton did @pickeditmate's suggestion help?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
