### ISSUE TITLE
trouble configuring YS1 with Rfcat 

### ISSUE THREAD

**Issue by slikkmulah** [greatscottgadgets/yardstick#24]
So yea, Im pretty new to linux but I just had a buddy of mine help me install RFCAT and when the time came to plug in my ys1 and get them paired up, my windows 10 laptop said that the device is not recognized and is malfunctioning and the ys1 had 0 LED's lighting up. I tried many things to get it working finally after a while i put it bootloader mode and my laptop finally was recognizing the device as "yard stick one bootloader".

So i got back to trying to flash it and I just cannot get the Rfcat software to recognize the ys1. I try and flash the YS1 in bootloader mode with the correct command for flashing it (cant remember exactly what that command is) and all i get back is "no dongle found" message. So I thought YS1 was broken/faulty so i order a new one and I go to plug the new YS1 in for the very first time and yet again, no LED's and the message saying that its unrecognized and malfunctioning. I tried  this on my pc too and same problem.

PLZ HELP! Thx.

**Comment by straithe** [comment]
Can you please post a screenshot of the error message you are getting?

**Comment by slikkmulah** [comment]
Yes, here you go.

**Comment by straithe** [comment]
You will have to visit the GitHub issue page and post a picture. Attaching the picture when replying by email does not work to add it to this thread.

**Comment by slikkmulah** [comment]
![069BB373-9A3A-4530-8843-EC132D638D16](https://user-images.githubusercontent.com/113897259/191101126-95576364-4998-4722-a6ba-6502a34caa2f.jpeg)

**Comment by slikkmulah** [comment]
Oh, sorry about that I haven’t  used the issue subsection before.

**Comment by slikkmulah** [comment]
Hello, do you have time to help me with this issue today?

**Comment by straithe** [comment]
Is this in a VM, or baremetal?

**Comment by slikkmulah** [comment]
I fixed this a long time ago. Thank you anyways though.
