### ISSUE TITLE
Yardstick not recognized by windows

### ISSUE THREAD

**Issue by zdovac123** [greatscottgadgets/yardstick#27]
Hello,

I have an issue conencting YardStick One to my pc Windows 10 computer, I purchased YardStick One in 2019 and it was hiding until now.
Now I wanted to play with it and somehow it is not recognized by windows, I tried updates and I guess I don't know how and where to get proper software to get it running

Thank you for your help in advance, Z123

**Comment by zdovac123** [comment]
So I found the issue, Windows 10 does not support YardStick One or I am just unable to find proper drivers, I pluged it in laptop with Windows 7 and it's plug and play. So Windows 7 FTW!!

**Comment by straithe** [comment]
Happy that worked for you! Is there anything you need assistance with?
