### ISSUE TITLE
Is there a step by step procedure on how to upgrade the firmware on the yardstick one?

### ISSUE THREAD

**Issue by gusevargas** [greatscottgadgets/yardstick#3]
I have two yardstick ones, both seem to need their firmware upgraded, is there a step by step procedure to accomplish that task, for someone, who perhaps did not spend years behind a Linux Box...?

**Comment by grvvy** [comment]
Install instructions can be found [here](https://github.com/atlas0fd00m/rfcat#installing-with-bootloader). Please report back if you need further assistance.

**Comment by trunkafunk** [comment]
I'm also having problems updating the firmware on MacOS.. I filed an issue within rfcat, is that correct?

**Comment by grvvy** [comment]
Yes that is a good place to look for firmware help.
