### ISSUE TITLE
Alternating send & receive in parallel

### ISSUE THREAD

**Issue by ocgltd** [greatscottgadgets/yardstick#30]
I am planning to use rfcom with my home automation program, and plan to build an interface to MQTT.  I would like the yardstick to be always listening for packets of interesting, but if my app wants to transmit something I would like it to transmit.

Can I run 2 python processes in parallel (one for tx one for rx)?  If not, can I stop the rx process, tx my new packet, then restart an rx process?  Is there a better way to do this?

**Comment by mossmann** [comment]
This is more of an rfcat question than a YARD Stick question, but I do not believe that rfcat would support a two-process solution; while one process has claimed the USB device, the other process would be unable to claim it. It would be easier to have a single Python process that stops RX before starting TX and vice versa.
