### ISSUE TITLE
YS1 stability.

### ISSUE THREAD

**Issue by frevoli** [greatscottgadgets/yardstick#31]
Hello, I'm trying to find out a little more about the oscillator on the YS1, particularly with regards to its stability/ppm drift.
Any help would be greatly appreciated.
Thanks
Matt

**Comment by straithe** [comment]
Can you please detail your questions here?

**Comment by frevoli** [comment]
What is the specification of YS1's local oscillator?

**Comment by frevoli** [comment]
Is it an TXC 48.0 MJE2?

**Comment by martinling** [comment]
There have been two different parts used for the 48MHz crystal:

- Revision 1 has TXC part number [7A-48.000MAAJ-T](https://txccrystal.com/images/pdf/7a.pdf)
- Revision 2 has Raltron part number [RH100-48.000-18-F-3030-TR](https://www.raltron.com/webproducts/specs/CRYSTAL/RH100-48.000-18-F-3030-TR.pdf)

Both have similar specifications:
- tolerance of ±30ppm at 25°C
- stability of ±30ppm over temperature range
- aging of up to ±3ppm/year

**Comment by frevoli** [comment]
Super helpful, thank you very much for your help
