### ISSUE TITLE
Yardstick one not getting detected, leds orange and red are dim stable when plugged in to any os

### ISSUE THREAD

**Issue by pjtchand** [greatscottgadgets/yardstick#5]
I had started updating the firmware of the yardstick one, but unexpectedly the update got failed with some error after that, I'm not able to detect the yardstick one in my different operating systems. If I plug it in, it will be stable with dim LEDs red and orange.
please help me out of this and define a proper way for updating the firmware.

![IMG_4341](https://user-images.githubusercontent.com/25766595/71311120-a1d8c180-2442-11ea-99f7-76c28ea565ae.JPG)

**Comment by ChildishTurbino** [comment]
So did you fix the issue?

**Comment by pjtchand** [comment]
Yes, I had fixed the issue, sorry for the inconvenience.

Thanks and regards,
GOPICHAND D

**Comment by ChildishTurbino** [comment]
May i ask how you fixed your issue? The LED's Come up the same on my YS1

**Comment by pjtchand** [comment]
I just used the jumper cable and shorted the mentioned ports as mentioned
in one of the websites.

**Comment by ChildishTurbino** [comment]
I'm guessing 7 and 9 to go into bootloader mode, but what did you do after that, i cant seem to get it to work.

**Comment by ChildishTurbino** [comment]
Any Guidance?

**Comment by pjtchand** [comment]
Yup I did the same, connected 7 & 9 pins to start bootloader and then ran the update script. I had successfully updated my Ys1 to latest firmware.

Best Regards,
GOPICHAND D

**Comment by ChildishTurbino** [comment]
May i ask Which Update Script if you remember, because i have gone through the steps more than 20 times and it still does not seem to work
