### ISSUE TITLE
Does not connect To Computer

### ISSUE THREAD

**Issue by ChildishTurbino** [greatscottgadgets/yardstick#6]
![image](https://user-images.githubusercontent.com/53124524/76038702-4f268600-5f18-11ea-9286-5f769ab5c3c8.jpg)
Only LED 2 and 3 On Out the Factory, The Yard stick One does not come up when I type “lsusb”. When I jump pin 7 and 9 to get to the boot loader it pops up but I can’t seem to flash it beaus it just dosent connect properly. It could be DOA

**Comment by grvvy** [comment]
Sorry for the late response to this. Are you still having issues in the bootloader mode?

**Comment by ChildishTurbino** [comment]
Yes I was, I did return the YARD Stick One in for a HackRF One though, Thank you, Appreciate It!
