### ISSUE TITLE
How to test the hardware

### ISSUE THREAD

**Issue by BG7YWL** [greatscottgadgets/yardstick#7]
I have produced several YARD Stick One, but I cannot test the hardware.
Like Ubertooth, does YARD have assembly test firmware?

**Comment by grvvy** [comment]
[Try rfcat?](https://github.com/atlas0fd00m/rfcat#installing-with-bootloader)

**Comment by BG7YWL** [comment]
Try to make the hardware by yourself, and want to test whether the hardware can run successfully.
Is there an assembly test firmware similar to ubertooth
