### ISSUE TITLE
USB Device malfunction

### ISSUE THREAD

**Issue by akuuka1** [greatscottgadgets/yardstick#8]
helllo world!
 USB device connected has malfunctioned windows does not recognize"
_is the prompt upon connection of out-of-the-box ... as a novice, what can i do to rectify/ Ty

**Comment by mossmann** [comment]
It is possible to use YARD Stick One on Windows if you first install [Zadig](https://zadig.akeo.ie/). We do our development on Linux, so the most reliable way to get YARD Stick One up and running is to do so on Linux.

**Comment by akuuka1** [comment]
Hey thank u so much for the reply- I got er sorted out, man I also
purchased the hack1rf- u guys make out standing products- can I ask you,
how or what can I do to increase the reception? Also , have u tried the
HackRf_test app for android? Its pretty cool- keep those Alist products
rolling!!!

Joshua ketola aka

AKUUKA

**Comment by mossmann** [comment]
Thanks for the kind words! I haven't tried the HackRF_Test app, but it looks like it comes from @demantz who does great work! I have used his RFAnalyzer.

If you need to increase receive sensitivity of your HackRF, try adjusting all three gain settings. The `hackrf_transfer -h` help output gives details about the range of those settings. Also selecting an appropriate antenna for your application can make a big difference. If those things aren't enough and you need a further boost for a weak signal, you can try an external LNA between the HackRF and antenna.

**Comment by akuuka1** [comment]
Hey thank you so much for your help,  im a little confused- I can adjust
the gains ? Is the a specific interface  You are referring to? I didn't
notice anything on the module Clearly I have  Some reading to do... Also
yes the office fantastic and I also use RFanalyzer,  Though I am very new
to the field and it's quite slow going I have a smalle module that I
purchased until 20 decimal increase amplifier  I will send you a picture it
looks pretty good.  Once again thank you your products or just kick ass if
you have any insight for me regarding the game in parameter changing  I
would love to know


Take care and hope to hear from you

**Comment by mossmann** [comment]
Sorry I overlooked your reply. The gain settings I was referring to (from `hackrf_transfer -h`) are:
```
	[-a amp_enable] # RX/TX RF amplifier 1=Enable, 0=Disable.
...
	[-l gain_db] # RX LNA (IF) gain, 0-40dB, 8dB steps
	[-g gain_db] # RX VGA (baseband) gain, 0-62dB, 2dB steps
```
They may be called different things depending on the software you use. There is some more information about them in the FAQ:
https://github.com/mossmann/hackrf/wiki/FAQ#making-sense-of-gain-settings

If you need further help with your HackRF One, please open an issue on the HackRF repo:
https://github.com/mossmann/hackrf/

**Comment by akuuka1** [comment]
Wow thank you , I really appreciate the reply- its such a broad field of
learning, doin my best tho

Cheers!

**Comment by Dougsworth** [comment]
Hi. I just got a yardstick one. I understand that its used with linux. Ive loaded up vmware on my laptop ith kalilinux but for some reason i get the usb is malfunctioned message when i plug it into my laptop. Any help please?

**Comment by Dougsworth** [comment]
![image](https://user-images.githubusercontent.com/40311007/111671820-4df48e00-87e7-11eb-989a-f8bc536db7c2.png)

zadig detects the yardstick one as a vmware usb device it seems. but i dont see it displayed in kali-linux with lsusb
