### ISSUE TITLE
Device might be DOA?

### ISSUE THREAD

**Issue by n0xa** [greatscottgadgets/yardstick#9]
My wife bought a YARD Stick One for me for Christmas, and things have been busy. I don't use Linux much at home, and it looked like getting it working under Windows or Mac was going to be problematic, so it's been shelved for a good 7-8 months.

I finally installed Kali on an older laptop, got RFCat installed, but it tells me there's no dongle attached. Upon checking dmesg, I see:

"new full-speed USB device number -n- using ehci-pci" followed by "device not accepting address -n-, error -32" and finally "unable to enumerate USB device" with an occasional "attempt power cycle" message in between them. This happens regardless the USB port I try to use. 

On my main desktop (running OpenBSD 6.9), the only thing that shows up in dmesg is "uhub5: device problem, disabling port -n-" and typical behavior for a device that's not supported by the kernel (such as the HackRF One) is 'ugen0 at uhub5 port 1 "Great Scott Gadgets HackRF One" ...' so it's unusual to have no device show up at all, just getting a port error. 

The 3-pin IC nearest LED2 on my YARD Stick One (a voltage regulator, maybe?) gets untouchably hot after about 30 seconds of being plugged in. Examining the product under a magnifier, it seems to be properly constructed, with no solder bridges or obvious component damage (scorch marks, cracked IC packages, etc). This is the first time I have tried to use it at all. I hadn't plugged it in to any computer before yesterday.

I did jumper pins 7 and 9 on P1 to see if enabling bootloader mode makes any difference. It does not change the behavior on my Kali Linux laptop.

Ideas?

**Comment by meeas** [comment]
So, I assume you are running into a few issues all at once.  

First off, Kali's rfcat package has been broken over the last two years, and I suspect still is.  They tried to modify the code to make it Python3 compatible and didn't fully test their changes.  I'm not sure if that is still the case or not, but I'd recommend removing the Kali package and installing it with `pip install rfcat`.  You can also try out my VM over at https://www.controlthings.io/platform which has a functional version of rfcat installed with all the required dependencies (which I think pip is missing one...)

Second, the default firmware that ships with the Yardstick is not recognized by Windows 10, so any attempts to use a Linux VM on top of Windows 10 will fail until you re-flash the Yardstick to a later version, which can only be done on Linux installed on bare metal.  I helped @tlas update the rfcat readme so flashing should be a little more clear that it was in the past.

It really is a great tool once you get it working, its just a little bit of a climb first.

I'd also recommend joining the GSG Discord server for further support.  I think that is monitored better, and I know for myself, that I'd probably see your response faster there.  You can do that here:

https://t.co/MjDOrCSaf5?amp=1

**Comment by straithe** [comment]
Just to clarify, GSG does encourage issues to be posted on GitHub and not in the Discord as the Discord is not monitored by any of the staff. Of course we do have wonderful community members, such as @meeas who are available to help. Saying that, we at GSG are a bit behind of GitHub issues right now and for that I apologize.

**Comment by n0xa** [comment]
I have installed rfcat via pip on my Pi4 Kali (which never had rfcat installed via the repositories) and when I plug in the YardStick One, I still see no sign of the kernel detecting it via lsusb or dmesg, and rfcat predictably says No dongle found.

Attached are two photos of the board. One is up-close to the component (circled) which is heating up. It gets too hot to touch in a matter of seconds. I noticed this when I felt a burning sensation unplugging it for the first time when I started trying to work with the device shortly before reporting the issue. The other photo is the entire component side of the board. If you need higher resolution, I'll have to take pictures of it in segments. 

![WIN_20210822_16_15_38_Pro](https://user-images.githubusercontent.com/23286114/130370310-e2ea5af5-e8f4-443c-8d52-69ac0b37a790.jpg)
![WIN_20210822_16_08_57_Pro](https://user-images.githubusercontent.com/23286114/130370311-4329aa71-9b7d-4037-9346-464146f7d431.jpg)

**Comment by straithe** [comment]
Can you send a picture of the back as well? Also, where was the device purchased?

**Comment by n0xa** [comment]
Reverse side of the board. My wife says she bought this and the HackRF One (which works great) from Hacker-Gadgets [.] com and when I asked her, she noted that it took several weeks to show up. I notice they do not seem to be on your "Where to buy" page at present time. This would have been purchased sometime in November 2020. Do I have a counterfeit??? The HRF1 works great.

![20210823_115953](https://user-images.githubusercontent.com/23286114/130490121-53af4885-ad85-4f4a-bd3a-b5fda94baee6.jpg)

**Comment by straithe** [comment]
It looks like both the HackRF and the YARD Stick you received might be knockoffs (based on the website in question), but it is hard to tell with the YARD Stick, and that's fine! :) It just helps with debugging and providing suggestions to know what the board looks like and where it was purchased from. 

In this case, the components do appear like they may have been hand soldered on, and the component that is heating up is the voltage regular, so I do feel you may have a short somewhere. In this case I typically recommend contacting the reseller to see if you can get an exchange. I'm not sure if the store your wife purchased from will provide that service though. If they won't do an exchange or return I suggest looking over the board thoroughly for a short and attempting to resolder the piece.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
